spring:
  datasource:
    url: jdbc:mysql://10.100.100.20:3306/rbac?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initialization-mode: always
    continue-on-error: true



#    schema:
#      - "classpath:db/schema.sql"
#    data:
#      - "classpath:db/data.sql"
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      max-lifetime: 60000
      connection-timeout: 30000




  main:
    allow-bean-definition-overriding: true
  application:
    name: security-rbac


#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: cn.iocoder.mall.order.biz.dataobject

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.eci.security.rbac.common.dataobject
server:
  port: 16666

logging:
  level:
    com.eci.security.rbac.dao: debug

